# Generated by Django 5.0 on 2024-01-12 08:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('mobile_no', models.CharField(max_length=12)),
                ('address1', models.CharField(max_length=250, verbose_name='')),
                ('address2', models.CharField(max_length=250, verbose_name='')),
                ('district', models.CharField(max_length=50, verbose_name='')),
                ('pin_code', models.IntegerField(verbose_name='')),
                ('state', models.CharField(max_length=50, verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
