# Generated by Django 5.0 on 2024-01-12 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0002_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='pin_code',
            new_name='pincode',
        ),
    ]
