# Generated by Django 5.0 on 2024-01-08 16:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('product_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField()),
                ('product_name', models.CharField(max_length=100, verbose_name='title')),
                ('price', models.CharField(max_length=50)),
                ('selling_price', models.FloatField(verbose_name='selling price')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='')),
                ('discount', models.FloatField(verbose_name='discount')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to='', verbose_name='')),
                ('categories', models.ManyToManyField(blank=True, null=True, to='productAPI.productcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
